version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: irede
      POSTGRES_USER: cauan
      POSTGRES_PASSWORD: cauan
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
